### ISSUE TITLE
[Mechanics] motor-wheel mount optimizations

### ISSUE THREAD

**Issue by Akustav** [ut-robotics/picr22-team-kivipallur-jurto#10]
You can make the mount smaller to make it simpler to create. You can make the mounting part shorter and also put the fastening hole in between the wheel mounting holes to avoid potential interference.

![image](https://user-images.githubusercontent.com/5435954/197332559-d9d9fc4e-3c0b-4a4c-bf73-924f9c71dbee.png)

**Comment by KMKgit** [comment]
Resolved. Reduced the length by 1mm. Cannot make it any shorter, otherwise the mounting screw wouldn't fit and it wouldn't be on the flattened part of the motor shaft.
