### ISSUE TITLE
[Mechanics] add hole for shaft to omniwheel body

### ISSUE THREAD

**Issue by Akustav** [ut-robotics/picr22-team-kivipallur-jurto#11]
You can add a hole to the omni wheel body where the shaft can move into. Currently this is the most compact you can make the assembly:

![image](https://user-images.githubusercontent.com/5435954/197332750-6d64fa0c-81da-42cb-96e1-b973f06e5e57.png)

with a hole, you can make it more compact:

![image](https://user-images.githubusercontent.com/5435954/197332797-39c4b6dd-a4a6-4942-84af-fa0a8cc94d7f.png)

**Comment by KMKgit** [comment]
resolved
