### ISSUE TITLE
[Mechanics] camera side legs cutouts

### ISSUE THREAD

**Issue by Akustav** [ut-robotics/picr22-team-kivipallur-jurto#13]
You have cutouts in the side panels for the camera mount. This can increase flex in the mount and make the camera vibrate more. Are they needed?

![image](https://user-images.githubusercontent.com/5435954/198689025-8e7739be-6999-47ff-aa11-77018af34a7c.png)

**Comment by KMKgit** [comment]
It's not essential, but it helps with cable management. I can perhaps make one smaller cutout.

**Comment by Akustav** [comment]
I suggest that to avoid excess vibrations and swaying.
