### ISSUE TITLE
[Mechanics] wrong hole size in camera mount

### ISSUE THREAD

**Issue by Akustav** [ut-robotics/picr22-team-kivipallur-jurto#14]
Threaded holes should be 2.5mm:

![image](https://user-images.githubusercontent.com/5435954/198689299-f309b46c-4ac2-4148-baea-ec26c387ca95.png)
![image](https://user-images.githubusercontent.com/5435954/198689350-91ac21c0-9eae-415e-8cdc-81192cea15fd.png)

**Comment by KMKgit** [comment]
Resolved
