### ISSUE TITLE
[Mechanics] Use chassis to support internal ramp

### ISSUE THREAD

**Issue by Akustav** [ut-robotics/picr22-team-kivipallur-jurto#28]
This is not necessarily a issue but more of a suggestion. I think you can use the chassis to support the internal ramp as well. Maybe add a lip that rests on the chassis, like this:

![image](https://user-images.githubusercontent.com/5435954/200117508-a6e90835-8db3-4ac2-930a-a68f98bde252.png)

Or cutouts from the bottom plate to support the ramps from the sides:

![image](https://user-images.githubusercontent.com/5435954/200117549-dfe951b2-2922-4f9a-822c-e296915b3e2f.png)

It is something to consider

**Comment by KMKgit** [comment]
Resolved

**Comment by Akustav** [comment]
If you add this lip, it is even more supported:

![image](https://user-images.githubusercontent.com/5435954/204079896-3067306c-0d6a-46f8-af07-641306019233.png)

**Comment by KMKgit** [comment]
resolved
