### ISSUE TITLE
[Mechanics] Thrower ramps interference with bottom plate

### ISSUE THREAD

**Issue by maidlam** [ut-robotics/picr22-team-kivipallur-jurto#4]
The ramps of the thrower interfere with the bottom plate.

![Fusion360_2022-09-15_12-58-01](https://user-images.githubusercontent.com/32770145/190377912-c3335c8f-7141-4cfa-a385-d7d84656709c.png)

One option might be to make a cutout so that the ramp fits over the plate.

![Fusion360_2022-09-15_13-04-58](https://user-images.githubusercontent.com/32770145/190377952-375850a2-5c55-4a05-8ca7-f1365024dcc3.png)

**Comment by KMKgit** [comment]
resolved
