### ISSUE TITLE
[Mechanics] Issues with 2D Pocket

### ISSUE THREAD

**Issue by maidlam** [ut-robotics/picr22-team-kivipallur-jurto#6]
1. Increase Maximum Stepover under Passes.
2. Increase Maximum roughing Stepdown in Multiple Depths to 1 mm.
3. Change Stock to Leave settings.

Use the same settings as in the guide
https://ut-robotics.github.io/picr22-home/basketball_robot_guide/mechanics/cam.html#_pocket

**Comment by KMKgit** [comment]
Resolved
