### ISSUE TITLE
[Mechanics] Issues with 2D Contour

### ISSUE THREAD

**Issue by maidlam** [ut-robotics/picr22-team-kivipallur-jurto#7]
1. Wrong contours selected for sliders.

![Fusion360_2022-09-25_19-50-57](https://user-images.githubusercontent.com/32770145/192155884-22eca758-d7c5-42df-8a30-13beaaa74296.png)

2. Reduce height of tabs.
3. Multiple depths missing.
4. Stock to Leave missing.
5. Lead-In and Lead-Out should be unticked.

Use the same settings for the Passes and Linking tabs as are in the 2D Pocket section
https://ut-robotics.github.io/picr22-home/basketball_robot_guide/mechanics/cam.html#_pocket

**Comment by KMKgit** [comment]
Resolved
